### ISSUE TITLE
When project name contains numbers, next PV number is incorrect

### ISSUE THREAD

**Issue by simonkrenger** [oscp/cloud-selfservice-portal-backend#10]
We encountered the following problem:
When creating a new Gluster volume using the Self-Service-Portal and the project name contains a number the second PV will have the wrong PV number.

I think this is due to the way the next PV number is calculated: https://github.com/oscp/cloud-selfservice-portal-backend/blob/51418e99fdd33b9b300bf66a038dae654346ec63/glusterapi/gluster/newvolumes.go#L141

Steps to reproduce:
* Using the SSP, create a new project, the name should contain a number (e.g. "a12345-myproject"
* Use the SSP to create a new Gluster volume. The first volume will be fine (named "a12345-myproject-pv1").
* Use the SSP to create another Gluster volume.

Expected result:
* A new PV is created with the name "a12345-myproject-pv2"

Actual result:
* A new PV is created with the name "a12345-myproject-pv12346"

**Comment by ReToCode** [comment]
Fixed in https://github.com/oscp/cloud-selfservice-portal-backend/releases/tag/v1.2.0
